<?php
/*
 * This file is part of the zyan/url2pic-sdk.
 *
 * (c) 读心印 <aa24615@qq.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Zyan\Tests;

use PHPUnit\Framework\TestCase;
use Zyan\UrlToPic\UrlToPic;

/**
 * Class UrlToPicTest.
 *
 * @package Zyan\Tests
 *
 * @author 读心印 <aa24615@qq.com>
 */
class UrlToPicTest extends TestCase
{
    protected $key;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->key = '11111111111111111111111111111111';
    }

    /**
     * 断言单页接口.
     *
     * @return void
     *
     * @author 读心印 <aa24615@qq.com>
     */
    public function testUrl2pic()
    {
        $app = new UrlToPic($this->key);

        $res = $app->url2pic('http://www.baidu.com');

        $this->assertIsArray($res);

        $this->assertArrayHasKey('code', $res);
        $this->assertEquals($res['code'], 1);
    }

    /**
     * 断言批量接口.
     *
     * @return void
     *
     * @author 读心印 <aa24615@qq.com>
     */
    public function testBatch()
    {
        $app = new UrlToPic($this->key);

        $res = $app->batch(['http://www.php127.com/','http://www.baidu.com']);

        $this->assertIsArray($res);
        $this->assertArrayHasKey('code', $res);
        $this->assertEquals($res['code'], 1);
    }

    /**
     * 断言查询结果.
     *
     * @return void
     *
     * @author 读心印 <aa24615@qq.com>
     */
    public function testStatus()
    {
        $app = new UrlToPic($this->key);

        $res = $app->status('task60765c9c5b827202104140308126');

        $this->assertArrayHasKey('code', $res);
        $this->assertEquals($res['code'], 1);
    }
}
